# codemagic.yaml
workflows:
  android-java-workflow:
    name: Android Java Build
    max_build_duration: 60
    environment:
      groups:
        - google_play
      android_signing:
        - timelead
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk'
        PACKAGE_NAME: "ug.go.health.ihrisbiometric"
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - .gradle/caches
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
            # fallback in case no build number was found from Google Play.
            # Alternatively, you can `exit 1` to fail the build
            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
            # of times this workflow has been built
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd android
          ./gradlew bundleRelease \
              -PversionCode=$UPDATED_BUILD_NUMBER \
              -PversionName=1.0.$UPDATED_BUILD_NUMBER 
    artifacts:
      - app/build/outputs/**/*.apk
