workflows:
  android-workflow:
    name: Build Android APK with OpenCV SDK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_BUILD: "true"
        OPENCV_SDK_PATH: "$HOME/OpenCV-android-sdk/sdk"


    scripts:
      # 1. Download the OpenCV Android SDK
      - name: Download OpenCV Android SDK
        script: |
          echo "Downloading OpenCV Android SDK..."
          curl -L https://github.com/opencv/opencv/releases/download/4.10.0/opencv-4.10.0-android-sdk.zip -o opencv-android-sdk.zip
          unzip opencv-android-sdk.zip
          export OPENCV_SDK_PATH=$(pwd)/OpenCV-android-sdk/sdk

      # 2. Set gradlew executable permissions
      - name: Set gradlew executable permissions
        script: |
          echo "Setting execute permissions for gradlew..."
          chmod +x ./gradlew

      # 3. Clean the project
      - name: Clean Project
        script: |
          echo "Cleaning project..."
          ./gradlew clean

      # 4. Build the Android app
      - name: Build APK
        script: |
          echo "Building APK with OpenCV..."
          ./gradlew assembleRelease

    artifacts:
      - build/app/outputs/apk/release/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - "your-email@example.com"
