# codemagic.yaml
workflows:
  android-opencv-workflow:
    name: Android OpenCV Build
    max_build_duration: 60
    environment:
      android_signing:
        - upload
      groups:
        - google_play
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - .gradle/caches
    scripts:
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
