# codemagic.yaml
workflows:
  android-java-workflow:
    name: Android Java Build
    max_build_duration: 60
    environment:
      android_signing:
        - timelead
      vars:
        PACKAGE_NAME: "ug.go.health.ihrisbiometric"
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - .gradle/caches
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: | 
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/**/*.apk
