# codemagic.yaml
workflows:
  android-opencv-workflow:
    name: Android OpenCV Build
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - .gradle/caches
        - ~/.opencv
    scripts:
      - name: Set up OpenCV Android SDK
        script: | 
          wget -q https://github.com/opencv/opencv/releases/download/4.8.0/opencv-4.8.0-android-sdk.zip
          unzip -q opencv-4.8.0-android-sdk.zip
          mkdir -p ~/.opencv
          mv OpenCV-android-sdk ~/.opencv/
          echo "opencv.sdk.dir=$HOME/.opencv/OpenCV-android-sdk" >> local.properties
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
